#!/usr/bin/env python3

import numpy as np
import scipy.signal as sp
from pyFOFlet import FOFlet
import matplotlib.pyplot as plt

from scipy.io.wavfile import write

from PyQt5 import QtWidgets, uic
import sys

class Ui(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui, self).__init__()
        uic.loadUi('./ui/MainWindow.ui', self)
        self.show()


#foflet1 = FOFlet.FOFlet()
app = QtWidgets.QApplication(sys.argv)
app.setStyle('kvantum')
window = Ui()
app.exec_()
