#!/usr/bin/env python3

import numpy as np
import scipy.signal as sp
import FOFlet
import matplotlib.pyplot as plt
import sounddevice as sd
from scipy.io.wavfile import write

def prt_str(foflet):
    pr_str = '''
FOFlet Parameters:
==================
alpha: | %8.5f
beta:  | %8.5f
k1:    | %8.5f
BW:    | %8d
Fc:    | %8d
Fs:    | %8d
Ts:    | %8.5f
==================
''' % (foflet.alpha, foflet.beta, foflet.k1, foflet.BW, foflet.Fc, foflet.Fs, foflet.Ts)

    print(pr_str)

imp = FOFlet.impulse()
imp.set_freq(100)

Fs = 44100
sd.default.samplerate = Fs

foflet = FOFlet.FOFlet()

foflet.update_FOFlet(10, 100, .002, 640, Fs, imp)

prt_str(foflet)

foflet2 = FOFlet.FOFlet()
foflet2.update_FOFlet(10, 120, .004, 1220, Fs, imp)

foflet3 = FOFlet.FOFlet()
foflet3.update_FOFlet(10, 100, .0015, 2240, Fs, imp)

foflet4 = FOFlet.FOFlet()
foflet4.update_FOFlet(10, 80, .002, 3050, Fs, imp)
plt.subplot(341)
plt.plot(foflet.FOFlet)
plt.subplot(342)
plt.plot(foflet2.FOFlet)
plt.subplot(343)
plt.plot(foflet3.FOFlet)
plt.subplot(344)
plt.plot(foflet4.FOFlet)


out = foflet.FOFlet + foflet2.FOFlet + foflet3.FOFlet + foflet4.FOFlet
plt.subplot(312)
plt.plot(out)
#plt.show()

f,t,Sxx = sp.spectrogram(out, nperseg=int(Fs/240), fs=Fs)
plt.subplot(313)
plt.pcolormesh(t, f, Sxx, shading='gouraud')
plt.ylabel('Frequency [Hz]')
plt.ylim(top=4000)
plt.xlabel('Time [sec]')
plt.savefig('output.png')

out = np.append(out, out)
out = np.append(out, out)
out = np.append(out, out)
out = np.append(out, out)
out = np.append(out, out)
out = np.append(out, out)
out = np.append(out, out)
out = np.append(out, out)
print(len(out))
write('test.wav', Fs, out)
